baseURL = 'https://azhao1981.github.io'
title = '我的博客'
theme = 'hugo-book'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
publishDir = 'public'

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1
[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2
[[menu.main]]
  name = "文档"
  url = "/docs/"
  weight = 3

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookRepo = 'https://github.com/azhao1981/azhao1981.github.io'
  BookEditPath = 'edit/main/content/'
  BookDateFormat = '2006-01-02'